---
version: '3'
services:
    redis:
        image: redis:latest
        container_name: stevend-redis
        ports:
            - 5050:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
    web:
        build: .
        container_name: stevend-web
        ports:
            - 5000:5000
        volumes:
            - ./data/animals.json:/animals.json
