---
apiVersion: v1
kind: Service
metadata:
  name: stevend-test-redis-service
  labels:
    username: stevend
    env: test
spec:
  type: ClusterIP
  selector:
    app: stevend-test-redis
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379
