---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    username: stevend
    env: test
spec:
  type: ClusterIP
  selector:
    app: helloflask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
