---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stevend-test-pvc-data
  labels:
    username: stevend
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

