---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloflask
  labels:
    app: helloflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloflask
  template:
    metadata:
      labels:
        app: helloflask
    spec:
      containers:
        - name: helloflask
          imagePullPolicy: Always
          image: stevendiep/test-flask:1.0
          env:
          - name: FLASK_APP
            value: "app.py"
          - name: REDIS_IP
            value: "10.109.90.27"
          ports:
          - name: http
            containerPort: 5000
